production:   false
debug:        false

app:
  root:       app
  coffee:     app/**/!(*Spec).coffee
  js:         app/!(lib)/**/*.js*]
  indexHtml:  app/index.html
  injectables:
    - app/lib/**/*.js
    - app/**/*.js
